### ISSUE TITLE
Please add license file and tag release

### ISSUE THREAD

**Issue by bignaux** [ghaerr/microwindows#29]
It would make easier to write package for linux distribution.

**Comment by embeddedt** [comment]
There is a LICENSE file inside the source directory: https://github.com/ghaerr/microwindows/blob/master/src/LICENSE

**Comment by bignaux** [comment]
Thanks, but better at root, btw , there is MPL 2.0, and it could be interesting to update (or not).

**Comment by ghaerr** [comment]
Thanks @bignaux! I've cleaned up some documentation and moved the LICENSE file to the root directory in preparation for a v0.95.0 release. I will tag a release 0.95.0 shortly.

With regards to possible MPL 2.0, I think for now it's best to leave the licensing as is, I need time  to study the transferability and possible contributor issues.

**Comment by bignaux** [comment]
https://github.com/NixOS/nixpkgs/pull/61837 nixpkgs derivation . it let see what stuff should be fix here.

**Comment by bignaux** [comment]
I've subscribed to release page. Nix can be use on lot of target (linux, darwin, ...). https://nixos.org/nix/download.html . Feel free to close this issue or keep it open if you have progress on failed démo nuklear, or better installation process.
