### ISSUE TITLE
Nano-X application screenshot-jpg not compiles when HAVE_JPEG_SUPPORT=Y in config file

### ISSUE THREAD

**Issue by JulStrat** [ghaerr/microwindows#31]
Hello, Greg !

My workaround
change line:116 in src/demos/nanox/Makefile from
  ifeq ($(FRAMEBUFFER), Y)
to 
  ifeq ($(SCREEN), FB)
I don't know if it's correct solution, but works for me.

Regards,

Julian.

**Comment by ghaerr** [comment]
Thanks, that is the proper fix! However, client-side direct framebuffer access was just added, which allows all applications mmap'd access to either a hardware framebuffer, or software framebuffer emulator. Thus, screenshot-jpg is now built whenever HAVE_JPEG_SUPPPORT=Y.
