### ISSUE TITLE
lex issue

### ISSUE THREAD

**Issue by rofl0r** [ghaerr/microwindows#50]
```
yacc -d fileio.y
Compiling y.tab.c...
lex fileio.l
"fileio.l":line 54: Error: Too many transitions 
Try using %a num
make[2]: *** [lex.yy.c] Error 1
```
i'm using posix compatible lex https://github.com/sabotage-linux/lex as lex program, and it requires that the maximum number of transitions be specified with the %a directive. apparently the build system assumes that lex is a symlink to flex oslt.

**Comment by ghaerr** [comment]
I think the contributed TinyWidgets is the only application that requires yacc/lex to compile.

You should be able to turn off the compilation of TinyWidgets by setting TINYWIDGETS=N in config.
Otherwise, it looks like you should be able to set LEX=<your lexer> in the src/contrib/TinyWidgets/tndesigner/Makefile./

**Comment by rofl0r** [comment]
i fixed the error with

```diff
--- a/src/contrib/TinyWidgets/tndesigner/fileio.l
+++ b/src/contrib/TinyWidgets/tndesigner/fileio.l
@@ -1,3 +1,4 @@
+%a 3000
 %{
 #include<tnWidgets.h>
 #include<math.h>
```

but then tinywidgets build choked on missing nanoX libraries (which i had disabled already), so i ended up disabling TINYWIDGETS as you proposed.

**Comment by rofl0r** [comment]
maybe the build config template could have something like

```
MICROWINDOWS=y
NANOX=y

ifeq $(NANOX, y)
TINYWIDGETS=y
...
endif
```

**Comment by ghaerr** [comment]
I fixed the lex issue with a commit.

> ifeq $(NANOX, y)
TINYWIDGETS=y
...
endif

Yes, that would work in this case, but there are many dependencies on various modules, and we're trying to keep code out of the config files. Thanks!
