### ISSUE TITLE
Missing file in makefile_nr for the drivers

### ISSUE THREAD

**Issue by djipi** [ghaerr/microwindows#52]
osdep.c file is not referenced in src\contrib\makefiles_nr\Makefile-drivers.
Does it is intended?

**Comment by ghaerr** [comment]
If you are saying that src/contrib/makefiles_nr/\* needs to have osdep.o added to it, please do and submit a PR.

I had thought that all the makefiles_nr were already converted to work for you with your last commits.

**Comment by djipi** [comment]
The src\contrib\makefiles_nr\Makefile-drivers is common to all platforms.
I can add the reference to osdep but does the other platforms (DOS_DJGPP, etc.) will require it as well?

**Comment by ghaerr** [comment]
> I can add the reference to osdep but does the other platforms (DOS_DJGPP, etc.) will require it as well?

Yes, that has been required for some time. The makefile_nr makefiles are not up to speed with changes that have been made in the last year to Microwindows, and are unfortunately only able to be tested well on special systems. Please add whatever is required for your build at this point.
