### ISSUE TITLE
Compile on Ubuntu for Emscripten

### ISSUE THREAD

**Issue by AdlIzzadin** [ghaerr/microwindows#55]
I cant compile MicroWindows on Ubuntu for Emscripten.

Linking mwapp.html ...
emcc  -O3 -I./nx11/X11-local -I/usr/include/freetype2 -I/usr/include/libpng16 -lfreetype -s USE_SDL=2 -s USE_ZLIB=1 -s USE_FREETYPE=1 -s USE_LIBPNG=1 -I/usr/include/freetype2 -I/usr/include/libpng16 -lfreetype  -Iinclude -I/usr/include/freetype2 -I/usr/include/libpng16 -lfreetype -DEMSCRIPTEN=1 -DMULTIAPP=1 -DHAVE_FREETYPE_2_SUPPORT=1	   -s WASM=0 -s TOTAL_MEMORY=67108864 -s ERROR_ON_UNDEFINED_SYMBOLS=0 -o bin/mwapp.html ./demos/mwin/mwapp.c ./demos/mwin/mwdemo.c ./demos/mwin/mwdemo2.c ./demos/mwin/mwmine.c ./images/demos/mwin/mwmine/mineflag.c ./images/demos/mwin/mwmine/mineface.c ./images/demos/mwin/mwmine/minefacelost.c ./images/demos/mwin/mwmine/minebomb.c ./images/demos/mwin/mwmine/minedone.c ./images/demos/mwin/mwmine/minehitfalse.c lib/libmwin.a
**wasm-ld: error: unknown file type: winmain.o**
emcc: error: '/home/proddik/Projects/emsdk/upstream/bin/wasm-ld -o /tmp/emscripten_temp_7l3m8tws/mwapp.wasm /home/proddik/Projects/emsdk/upstream/emscripten/cache/wasm/libfreetype.a /home/proddik/Projects/emsdk/upstream/emscripten/cache/wasm/libfreetype.a /home/proddik/Projects/emsdk/upstream/emscripten/cache/wasm/libfreetype.a -L/home/proddik/Projects/emsdk/upstream/emscripten/system/local/lib -L/home/proddik/Projects/emsdk/upstream/emscripten/system/lib -L/home/proddik/Projects/emsdk/upstream/emscripten/cache/wasm /tmp/emscripten_temp_7l3m8tws/mwapp_0.o /tmp/emscripten_temp_7l3m8tws/mwdemo_1.o /tmp/emscripten_temp_7l3m8tws/mwdemo2_2.o /tmp/emscripten_temp_7l3m8tws/mwmine_3.o /tmp/emscripten_temp_7l3m8tws/mineflag_4.o /tmp/emscripten_temp_7l3m8tws/mineface_5.o /tmp/emscripten_temp_7l3m8tws/minefacelost_6.o /tmp/emscripten_temp_7l3m8tws/minebomb_7.o /tmp/emscripten_temp_7l3m8tws/minedone_8.o /tmp/emscripten_temp_7l3m8tws/minehitfalse_9.o lib/libmwin.a /home/proddik/Projects/emsdk/upstream/emscripten/cache/wasm/libSDL2.a /home/proddik/Projects/emsdk/upstream/emscripten/cache/wasm/libpng.a /home/proddik/Projects/emsdk/upstream/emscripten/cache/wasm/libz.a /home/proddik/Projects/emsdk/upstream/emscripten/cache/wasm/libfreetype.a /home/proddik/Projects/emsdk/upstream/emscripten/cache/wasm/libgl.a /home/proddik/Projects/emsdk/upstream/emscripten/cache/wasm/libc.a /home/proddik/Projects/emsdk/upstream/emscripten/cache/wasm/libcompiler_rt.a /home/proddik/Projects/emsdk/upstream/emscripten/cache/wasm/libc++-noexcept.a /home/proddik/Projects/emsdk/upstream/emscripten/cache/wasm/libc++abi-noexcept.a /home/proddik/Projects/emsdk/upstream/emscripten/cache/wasm/libdlmalloc.a /home/proddik/Projects/emsdk/upstream/emscripten/cache/wasm/libpthread_stub.a /home/proddik/Projects/emsdk/upstream/emscripten/cache/wasm/libc_rt_wasm.a /home/proddik/Projects/emsdk/upstream/emscripten/cache/wasm/libsockets.a -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --allow-undefined --import-memory --strip-debug --export-table --export main --export stackSave --export stackRestore --export stackAlloc --export __data_end --export __wasm_call_ctors --export __errno_location --export malloc --export free --export setThrew --export realloc --export testSetjmp --export saveSetjmp --export memalign --export memset --export emscripten_GetProcAddress --export strstr -z stack-size=5242880 --initial-memory=67108864 --no-entry --max-memory=67108864 --global-base=1024' failed (1)

How fix it?

**Comment by AdlIzzadin** [comment]
My Emscripten version 2.0.6

**Comment by ghaerr** [comment]
Hello @AdlIzzadin,

That is rather strange... have you tried removing lib/libmwin.a and trying the compile again? It seems the archive library contains .o files of the wrong format/build.

I don't have the EMSDK on the system I am on now so I can't repeat the bug yet, as I am traveling, I am sorry.

Thank you!
