### ISSUE TITLE
Linker Error

### ISSUE THREAD

**Issue by UsNizami** [ghaerr/microwindows#79]
I am using it for first time and I am following the instruction given in src/README 
I have run `cp Configs/config.linux-X11 config` and then `make` but it give me this error . And I have not made any changes to code.

![Screenshot from 2023-09-26 15-41-26](https://github.com/ghaerr/microwindows/assets/49267403/79ff769c-e273-4402-bd8d-2a206019f417)

gcc version = 11.3.0
GNU Make = 4.3

Please help me fix this issue.

**Comment by ghaerr** [comment]
Hello @UsNizami,

This error is a result of both nxres and nyres being declared as `MWCOORD nxres; MWCOORD nyres;` in nanox/srvmain.c as well as drivers/scr_x11.c. The C compiler should allow both but seems not to in version 11.

I would suggest for the time being changing the drivers/scr_x11.c source to extern declarations as follows:
```
/* externally set override values from nanox/srvmain.c*/
extern MWCOORD nxres;          /* requested server x res*/
extern MWCOORD nyres;          /* requested server y res*/
```

Try that and lets see what happens. If this or similar errors continue, we will need to use the gcc `-fcommon` option using `EXTRAFLAGS=-fcommon` in the config file to allow common declarations. This is discussed in more detail in https://stackoverflow.com/questions/69908418/multiple-definition-of-first-defined-here-on-gcc-10-2-1-but-not-gcc-8-3-0.

Thank you!

**Comment by UsNizami** [comment]
Thanks for your help but now agter making those changes I am getting this strange error
![image](https://github.com/ghaerr/microwindows/assets/49267403/6f74188e-a95f-42e2-9e0e-0b5f7cd17098)

`shap.h` file is prasent as you can see in the screenshot. Still it is saing no "such file". Is there some issue in makefiel where its include path is specified?

**Comment by UsNizami** [comment]
I have fixxed that issue by corecting the path in Shape.c and Xinerama.c files. But now I am getting huge linker error "multiple definition of  ..." 

![Screenshot from 2023-09-27 14-38-55](https://github.com/ghaerr/microwindows/assets/49267403/703b5af9-ca56-4cb1-a71f-4d652096b87f)

What is a way to fix this issue ?

**Comment by ghaerr** [comment]
> But now I am getting huge linker error "multiple definition of ..."

It looks like this is the same error as the original problem, which is fixed using `-fcommon`. It now seems to be failing on compiling TinyWidgets, which is a 3rd party library. This library is rarely needed, so you can likely fix this problem by setting `TINYWIDGETS=N` in the config file.

The TinyWidgets library is the last library to be compiled and actually isn't required: this means that everything else is completed and can be tested, even without the suggested fix.

**Comment by UsNizami** [comment]
I worked by downgrading to gcc 10 and `TINYWIDGETS=N`. Thanks for your help.
