### ISSUE TITLE
font has background

### ISSUE THREAD

**Issue by ChauncyZhang** [ghaerr/microwindows#87]
Hi, I found a question when I use nano-x to develop an desktop app. 
My device is a edge device, so it only has linux-fb.
When I draw a text, I found font has black background, so how can I make it transparent? thx.
like that.
![2d25704b8102b6ae87eca17a4787704](https://github.com/ghaerr/microwindows/assets/168976284/c34f345b-a2b9-446f-bf67-0803334f2daa)

**Comment by ChauncyZhang** [comment]
here is the code
 `GR_FONT_ID font = GrCreateFontEx(GR_FONT_SYSTEM_VAR, 100,100, NULL);
    GrSetGCFont(gc, font);
    GrText(wid, gc, x, y, buffer, strlen(buffer), GR_TFUTF8);`

**Comment by ghaerr** [comment]
When a font glyph is drawn the foreground bits are drawn with the fg color, and the background bits with the bg color. Try turning off the background color being drawn using:
```
GrSetGCUseBackground(gc, 0);
```
This should cause only the foreground bits of the font to be drawn.

**Comment by ChauncyZhang** [comment]
OK，Thank you！That's cool!
